nervosnetwork/overlord

src/lib.rs
src/smr/mod.rs
src/smr/smr_types.rs
src/smr/state_machine.rs
src/state/process.rs
src/types.rs

This PR does:
* refactor counting signed votes and generate the aggregated vote
* develop check votes and QC after monitor prevote vote or precommit vote event
* derive display for structs and enums

refactor(state): counting signed votes and generate aggregated vote

---

src/error.rs
src/overlord.rs
src/state/mod.rs
src/state/process.rs
src/state/tests/event_test.rs
src/state/tests/message_test.rs
src/state/tests/mod.rs
src/state/tests/test_utils.rs
src/types.rs
src/utils/auth_manage.rs
src/utils/rand_proposer.rs

This PR does:
* develop unit tests of state module
* refactor interface arguments
* impl `std::error::Error` for consensus error

feat(test): develop unit tests of state module

---

Cargo.toml
src/lib.rs
src/overlord.rs
src/state/process.rs
src/state/tests/message_test.rs
src/state/tests/test_utils.rs
tests/test_utils.rs

This PR does:
* develop context environment by using [creep](https://github.com/zeroqn/creep).

feat(context): develop context environment of overlord

---

src/lib.rs
src/overlord.rs
src/state/process.rs
src/state/tests/mod.rs
src/state/tests/test_utils.rs
tests/test_utils.rs

This PR does:
* refactor the trait constraint of the `Consensus` interface

refactor(interface): change the trait constraint of interface

---

Cargo.toml

This PR does:
* update creep version

chore(cargo): update creep version

---

src/lib.rs
src/state/process.rs
src/state/tests/test_utils.rs
tests/test_utils.rs

This PR does:
* refactor overlord interface argument

refactor(trait): interface argument

---

src/lib.rs
src/state/process.rs

This PR does:
* fix panic when start running overlord

fix: panic when start running overlord

---

README.md
src/lib.rs

This PR does:
* prepare to release 0.1.0

doc: prepare to release 0.1.0

---

Cargo.toml
examples/salon.rs
src/lib.rs
src/overlord.rs
src/smr/mod.rs
src/smr/state_machine.rs
src/state/process.rs
src/state/tests/event_test.rs
src/timer.rs

This PR does:
* rename some functions and variables
* unified code style
* handle timer error

refactor: rename and optimize

---

README.md
src/smr/state_machine.rs
src/state/process.rs

This PR does:
* add a gap for future proposals and votes
* fix a bug may cause commit error
* more stringent self-check logic

 fix: add gap for future proposals and votes

---

Cargo.toml
src/smr/state_machine.rs
src/state/process.rs

This PR does:
* develop moodyblues trace

feat: develop moodyblues trace

---

src/smr/state_machine.rs
src/smr/tests/new_epoch_test.rs
src/smr/tests/proposal_test.rs
src/state/process.rs

This PR does:
* fix handle check epoch response process
* fix self-check process

fix: handle check epoch response process

---

Cargo.toml
src/codec.rs
src/state/collection.rs
src/state/process.rs
src/state/tests/mod.rs
src/types.rs

This PR does: 
* refactor: vote struct

refactor(types): vote struct for aggregate crypto

---

Cargo.toml
examples/salon.rs
tests/test_utils.rs

This PR does: 
* bump bytes version 0.4 -> 0.5

chore: update bytes version

---

src/smr/state_machine.rs
src/smr/tests/proposal_test.rs

This PR does:
* fix a bug in SMR module that may cause inactivation

fix(SMR): remove an outdated check

---

examples/salon.rs
src/lib.rs
src/overlord.rs
src/state/process.rs
src/wal/tests/util.rs
src/wal/tests/wal_test.rs

This PR does:
* change the overlord interface argument
* change the mutability for wal interface

refactor: wal interface argument

---

src/state/process.rs

This PR does:
* fix panic when saving wal after prevote or precommit event
* fix lose whole epoch error when saving wal

fix:panic and lose whole epoch error

---

src/state/process.rs

This PR does:
* print leader address tolog

feat(log): print leader address

---

Cargo.toml
examples/salon.rs
src/smr/mod.rs
src/smr/tests/new_epoch_test.rs
src/smr/tests/precommit_test.rs
src/smr/tests/prevote_test.rs
src/smr/tests/proposal_test.rs
src/state/process.rs
src/timer.rs
src/wal/tests/wal_test.rs

This PR does:
* change to tokio runtime

chore(runtime): change to tokio runtime

---

Cargo.toml
src/state/process.rs
src/types.rs
src/utils/auth_manage.rs
src/utils/rand_proposer.rs

This PR does:
Add another poll leader feature as the default leader choosing method. If wants to choose leader randomly, use `features = "random_leader"`.

feat: add another poll leader feature

---

examples/salon.rs
src/codec.rs
src/error.rs
src/lib.rs
src/overlord.rs
src/smr/mod.rs
src/smr/smr_types.rs
src/smr/state_machine.rs
src/smr/tests/new_height_test.rs
src/smr/tests/precommit_test.rs
src/state/collection.rs
src/state/process.rs
src/timer.rs
src/types.rs
src/utils/timer_config.rs
src/wal/tests/wal_test.rs

This PR does:
* develop brake engine

feat: develop brake engine

---

examples/salon.rs
src/codec.rs
src/overlord.rs
src/state/process.rs
src/types.rs
src/wal/tests/wal_test.rs

This PR does:
* refactor log info 
* remove some useless code

refactor: log info and remove useless code

---

src/state/process.rs

This PR does:
* vote for empty hash

refactor(state): vote for empty hash

---

src/state/process.rs
src/types.rs

This PR does:
Add pause process, stop running overlord when lost consensus power.

feat: pause overlord when lost consensus power

---

src/state/process.rs
src/timer.rs

This PR does:
* filter status that le self height 
* change max timeout coef into 5
* leader check prevote votes after broadcast proposal

refactor: filter le self height status

---

src/state/process.rs

This PR does:
* fix handle empty signed vote may cause inactivation
* refactor `check_full_txs` and  `try_get_full_txs`

fix: get check block result process

---

src/state/process.rs
src/wal/wal_type.rs

This PR does:
* derive Display for `WalInfo`

feat(wal): derive display for wal info

---

src/lib.rs
src/utils/auth_manage.rs

* add: extract_voters to calc voters from given nodes and bit_map
* test: add extract_voters test

feat(auth_manage): add extract_voters

---

src/smr/state_machine.rs
tests/integration_tests/mod.rs
tests/integration_tests/primitive.rs
tests/integration_tests/run.rs
tests/integration_tests/utils.rs
tests/integration_tests/wal.rs

It should vote depends on lock not straightly for nil after propose timeout.

fix(consistency): fix consistency bug

---

examples/salon.rs
src/error.rs
src/lib.rs
src/state/process.rs
tests/integration_tests/primitive.rs
tests/test_utils.rs

This PR does:
* add an overlord error handle

feat: add overlord error reporter

---

src/state/collection.rs
src/state/process.rs

This PR does:
* `ProposalCollector` add context when inserting proposal

refactor(collection): proposal collector add context

---

src/overlord.rs

fix: return ChannelErr instead of Ok

---

src/state/collection.rs

This PR does:
Use `HashMap` to store the `SignedChoke` in which the key is voter address and the value is `SignedChoke`.This can guarantee that only one choke of the same address can be saved in the choke collection.

fix(collection): use HashMap to store the signed chokes

---

Cargo.toml
examples/salon.rs
src/lib.rs
src/smr/smr_types.rs
src/state/process.rs
src/types.rs
tests/integration_tests/primitive.rs
tests/test_utils.rs

This PR does:
Add the report view change reason interface.

feat: add the report view change reason interface

---

src/lib.rs
src/utils/auth_manage.rs

This PR does:
* Add an interface to get the leader with the corresponding height and round.

feat(utils): add get leader interface

---

src/timer.rs

The pending break flag must be reset by every loop, otherwise, it will cause some delay on the channel message.
Consider a scenario:
```
Loop 1:
a pending => set to false
b ready => keep true
Loop 2.
a ready => but keep false
b pending => set to false
```
We should continue polling here, but the previous code, where would be broken here 
If we need to manually control the number of times the timer loops, then we can do this:
```rust
let mut need_wake = false
for _ in 0..64 {
set need_wake here
}
if need_wake {
cx.waker().wake_by_ref()
}
```
similar like [this](https://github.com/driftluo/tentacle/blob/master/yamux/src/session.rs#L649-L686)

refactor(timer): rewrite timer state machine loop
